name: Build

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node 10
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install deps
      run: |
        npm install -g gulp
        npm install

    - name: Build
      run: |
        gulp
        gulp build

    - name: Deploy Build
      uses: docker://peaceiris/gh-pages:v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: deploy
        PUBLISH_DIR: ./dist
      with:
        emptyCommits: false
